---
- name: Configuring Node 3
  hosts: node3
  strategy: free
  gather_facts: yes
  ignore_errors: yes
  tasks:
  - name: Setting Hostname
    hostname: name=node3.ansi.example.com
  - name: Creating Ansible User
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Checking Sudoers Configuration
    lineinfile:
      path: /etc/sudoers
      regexp: '^# %users  localhost'
      insertafter: '^# %users  localhost'
      line: 'user ALL=(ALL) NOPASSWD: ALL'
      state: present
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n192.168.55.60 repo.ansi.example.com repo\n192.168.55.60 control.ansi.example.com control\n192.168.55.61 node1.ansi.example.com node1\n192.168.55.62 node2.ansi.example.com node2\n192.168.55.63 node3.ansi.example.com node3"
      force: yes
  - name: Configuring network
    command: nmcli con mod "System eth0" ipv4.addresses 192.168.55.63/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Restarting Network
    service: name=NetworkManager state=restarted
  - name: Removing Existing RSA Key
    shell: rm -f /home/user/.ssh/id_rsa
  - name: Generating RSA Key
    command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
    args:
      creates: /etc/ssh/ssh_host_rsa_key
    ignore_errors: yes
  - name: Fixing Resolv File
    shell: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
  - name: Enabling services
    service: name=firewalld enabled=yes state=started
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '       
        #           _            _           _           _         _          
        #          /\ \     _   /\ \        /\ \        /\ \     /\ \         
        #         /  \ \   /\_\/  \ \      /  \ \____  /  \ \   /  \ \        
        #        / /\ \ \_/ / / /\ \ \    / /\ \_____\/ /\ \ \ / /\ \ \       
        #       / / /\ \___/ / / /\ \ \  / / /\/___  / / /\ \_/ / /\ \ \      
        #      / / /  \/____/ / /  \ \_\/ / /   / / / /_/_ \/_\/_//_\ \ \     
        #     / / /    / / / / /   / / / / /   / / / /____/\    __\___ \ \    
        #    / / /    / / / / /   / / / / /   / / / /\____\/   / /\   \ \ \   
        #   / / /    / / / / /___/ / /\ \ \__/ / / / /______  / /_/____\ \ \  
        #  / / /    / / / / /____\/ /  \ \___\/ / / /_______\/__________\ \ \ 
        #  \/_/     \/_/\/_________/    \/_____/\/__________/\_____________\/ 
        '"#
        #
        # You are logged into \"`hostname`\" as user \"`whoami`\"
        # This system is running `cat /etc/redhat-release`
        #
        "
...