---
- name: Configuring Repo Server
  hosts: repo
  strategy: free
  gather_facts: false
  ignore_errors:
  tasks:
  - name: Setting Hostname
    hostname: name=repo.ansi.example.com
  - name: Creating Ansible User
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Checking Sudoers Configuration
    lineinfile:
      path: /etc/sudoers
      regexp: '^# %users  localhost'
      insertafter: '^# %users  localhost'
      line: 'user ALL=(ALL) NOPASSWD: ALL'
      state: present
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n192.168.55.60 repo.ansi.example.com repo\n192.168.55.60 control.ansi.example.com control\n192.168.55.61 node1.ansi.example.com node1\n192.168.55.62 node2.ansi.example.com node2\n192.168.55.63 node3.ansi.example.com node3"
      force: yes
  - name: Starting Firewalld
    service: name=firewalld state=started enabled=yes
  - name: Enabling Firewall Services
    firewalld: 
      service: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    with_items:
      - http
      - https
      - ntp
      - dns
      - kerberos
      - ldap
      - ldaps
      - ftp
  - name: Starting services
    service: 
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - httpd
      - firewalld
      - chronyd
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #           _          _           _         _       
         #          /\ \       /\ \        /\ \      /\ \     
         #         /  \ \     /  \ \      /  \ \    /  \ \    
         #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \   
         #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \  
         #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\ 
         #     / / /__\/ // /____/\   / / /__\/ / / /   / / / 
         #    / / /_____// /\____\/  / / /_____/ / /   / / /  
         #   / / /\ \ \ / / /______ / / /     / / /___/ / /   
         #  / / /  \ \ / / /_______/ / /     / / /____\/ /    
         #  \/_/    \_\\/__________\/_/      \/_________/     
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into `hostname`
         # This system is running `cat /etc/redhat-release`
         #
         # You are logged in as `whoami`
         #
         "
  - name: Disabling services then rebooting
    selinux: 
      state: disabled
  - name: Rebooted Server
    reboot:
...